### ISSUE TITLE
Configuration tab isn't woking in normal

### ISSUE THREAD

**Issue by cks3443** [Vardot/varbase-build#2]
I installed web with varbase-build:8.x
The below is error log when configuratio tab is opened.

[Sun Jul 10 14:37:17.415537 2016] [:error] [pid 9160] [client 127.0.0.1:54634] Uncaught PHP Exception RuntimeException: "/var/www/html/vb84_install/docroot/composer.json is not readable." at /var/www/html/vb84_install/docroot/modules/contrib/composer_manager/src/JsonFile.php line 21, referer: htt

**Comment by cks3443** [comment]
I switch vendor folder location outside docroot into docroot ... now configuration tab is working
so we need to modify vendor location when install

**Comment by Natshah** [comment]
Ok then. search for vendor in the varbase-build files.
